services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Port 5000 backend mapping
    environment:
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
      - TZ=Europe/Warsaw  # Set the timezone


  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Port 80 front-end container mapping
    depends_on:
      - backend  # Ensures that the frontend starts up after the backend
