services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Port 5000 backend mapping
    volumes:
      - ./backend:/app  # Allows you to edit files locally
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Port 80 front-end container mapping
    depends_on:
      - backend  # Ensures that the frontend starts up after the backend
